// <auto-generated/>
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace InventorySystem.Web.Shared
{
    public partial class ProductFormDialog
    {
        [CascadingParameter]
        public IMudDialogInstance mudDialog { get; set; }

        // Mutable class for the form UI
        protected ProductFormDialog mode = new ProductFormDialog();
        protected bool success;
        protected MudForm form = null;

        [Obsolete]
        protected void Submit()
        {
          form.Validate();

        }
    }
}